import re

def decode_garbled(text):
    out = []
    for c in text:
        if c == 'À':
            out.append('fi')
        elif c == 'Á':
            out.append('fl')
        elif c == 'µ':
            out.append('"')
        elif c == '´':
            out.append('"')
        elif c == '²':
            out.append('2')
        elif c == '¶':
            out.append("'")
        elif c == '·':
            out.append("'")
        elif 33 <= ord(c) <= 95 and c not in ['|', '#', '-', '*', '>', '<']:
            out.append(chr(ord(c) + 29))
        else:
            out.append(c)
    return "".join(out)

with open('docs/gazettes/5667.md', 'r') as f:
    text = f.read()

garbled_patterns = [
    r'7HOHFRP 1DPLELD \/LPLWHG KHUHLQDIWHU UHIHUUHG WR DV ´7HOHFRP 1DPLELDµ ÀOHG IRU WKH DSSURYDO',
    r'EHWZHHQ 0ERN ,QYHVWPHQWV \&RPSDQ\\ \/WG RQ ÀOH ZLWK WKH \$XWKRULW\\ DQG 1\&\& IRUPV WKH',
    r'D EDFNJURXQG RQ LWV VWUXFWXUH DQG DIÀOLDWLRQV UDLVLQJ VHYHUDO TXHVWLRQV LQ UHODWLRQ WR GLJLWDO',
    r'FRUUHVSRQGHQFH RQ ÀOH WKDW GHPRQVWUDWHV 0ERN ,QYHVWPHQWV \&RPSDQ\\ \/WG ·V GHVLUH LV WR',
    r'F \&HUWLÀHG FRSLHV RI FRPSDQ\\ UHJLVWUDWLRQ',
    r'G 6WDWHPHQW RI DFFRXQWV VHWWLQJ RXW ÀQDQFLDO UHVRXUFHV DYDLODEOH DQG',
    r'WKDW ZLOO EH DIIHFWHG ÀQDQFLDOO\\ VKRXOG D FRPPHUFLDO EURDGFDVWLQJ VHUYLFH OLFHQFH QRW EH',
    r'F 7KDW WKH \$XWKRULW\\ VKRXOG FRQÀUP WKH QDWLRQDOLW\\ RI WKH DSSOLFDQW ZLWK WKH 0LQLVWU\\',
    r'D MXULVWLF SHUVRQ RI ZKLFK DW OHDVW SHUFHQW RI WKH VKDUHKROGLQJ LV EHQHÀFLDOO\\',
    r'RU UHJLVWHUHG RIÀFH LQ 1DPLELD',
    r'\$XWKRULW\\ LQGLFDWHV WKDW ÀYH RI 0U 0ERN·V FKLOGUHQ DUH WKH EHQHÀFLDULHV \+RZHYHU WKH \$XWKRULW\\ REWDLQHG D FHUWLÀHG FRS\\ RI WKH 7UXVW \'HHG IURP WKH RIÀFH RI WKH 0DVWHU ZKLFK UHÁHFWV WKDW IRXU RI 0U 0ERN·V FKLOGUHQ DUH WKH EHQHÀFLDULHV RI WKH 0ERN \)DPLO\\ 7UXVW',
    r'´7KH RIÀFH RI D WUXVWHH VKDOO EH GHHPHG WR KDYH EHHQ YDFDWHG LI WKH PDMRULW\\ RI WKH 7UXVWHHV WKHQ LQ RIÀFH E\\ ZULWWHQ LQVWUXPHQW UHTXLUHV KLP RU KHU WR UHVLJQ 3URYLGHG WKDW LW VKDOO QRW EH FRPSHWHQW IRU WKH RWKHU 7UXVWHHV WR UHTXLUH WKH IRXQGHU WR UHVLJQ DV',
    r'WKH DSSURSULDWLRQ RI LQFRPH DQG FDSLWDO RI WKH 7UXVW IRU WKH HGXFDWLRQ RI WKH EHQHÀFLDULHV',
    r'VKDUHKROGHUV 7KH HOHPHQWV RI D WUXVW DUH D IRXQGHU D WUXVWHH DQG D EHQHÀFLDU\\ 7KH FRPPRQ',
    r'SURYLVLRQV RI VHFWLRQ E LV ZKHWKHU WKH VKDUHKROGLQJ LQ \'LJLVDW LV EHQHÀFLDOO\\ RZQHG',
    r'D 7KDW DW OHDVW SHU FHQW RI LWV VKDUHKROGLQJ LV EHQHÀFLDOO\\ RZQHG E\\ 1DPLELDQ',
    r'7KH EHQHÀFLDO RZQHUVKLS RI \'LJLVDW',
    r'RZQV WKH VKDUHV IRU LWV RZQ EHQHÀW RU ZKHWKHU WKH EHQHÀW LQ WKH VKDUHKROGLQJ LV HQMR\\HG E\\',
    r'E 7KH EHQHÀFLDULHV DUH 0U 0ERN·V ÀYH FKLOGUHQ \-XQH DPHQGPHQW SUHYLRXVO\\ IRXU EHQHÀFLDULHV 0DUFK GHHG',
    r'EHQHÀFLDOO\\ RZQHG',
    r'0ERN \)DPLO\\ 7UXVW DQG GHWHUPLQH WR ZKRP WKH VKDUHKROGLQJ EHQHÀWV DFFUXH 7KH \$XWKRULW\\',
    r'WR GHWHUPLQH WKH TXHVWLRQ RI YHVWLQJ RI WKH EHQHÀWV RI WKH 7UXVW',
    r'FRQWDLQV D GHÀQLWLRQ RI FRQWURO \+RZHYHU DQ DVVHVVPHQW RI WKH ZRUG UHYHDOV WKH IROORZLQJ',
    r'KDYLQJ D GHÀQLWH RU GHVLUHG HIIHFW 3RZHUIXO LQ HIIHFW LPSUHVVLYH DFWXDO H\[LVWLQJ LQ IDFW UDWKHU WKDQ RIÀFLDOO\\ RU WKHRUHWLFDOO\\',
    r'PHUHO\\ FRQVWLWXWH WKHRUHWLFDO PDQDJHPHQW EXW QRW SURYH DFWXDO RU RIÀFLDO PDQDJHPHQW',
    r'\'RHV \'LJLVDW KDYH D SODFH RI EXVLQHVV RU UHJLVWHUHG RIÀFH LQ 1DPLELD',
    r'L 7KH \&RPSDQLHV \$FW \$FW 1R RI GHÀQHV D ¶SODFH RI EXVLQHVV· WR PHDQ',
    r'VKDUH WUDQVIHU RU VKDUH UHJLVWUDWLRQ RIÀFH µ',
    r'LL 7KH \$XWKRULW\\ QRWHV WKDW GXULQJ WKH ZHHN RI ² \-DQXDU\\ WKH \&RQÀGDQWH QHZVSDSHU',
    r'KH HQWHUHG LQWR ZLWK KLV VHHPLQJO\\ GLVVDWLVÀHG FOLHQWV WR RIIHU FHUWDLQ VHUYLFHV ZKLFK KH DSSDUHQWO\\ GLG QRW IXOÀOO \\HW KH LV DSSDUHQWO\\ GHGXFWLQJ VSHFLÀF DPRXQWV IURP WKHLU DFFRXQWV',
    r'LLL \$FFRUGLQJ WR WKH \&RQÀGDQWH RQH FOLHQW FODLPV QRW WR KDYH KDG DQ\\ NQRZOHGJH WKDW VKH',
    r'WKDW \'LJLVDW LV UHFHLYLQJ SD\\PHQWV IURP KHU IRU EURDGFDVWLQJ VHUYLFHV DQG VKH LV QRW VDWLVÀHG',
    r'UHÁHFWLQJ GHGXFWLRQV WR \'LJLVDW LQ WKLV UHJDUG',
    r'L \'LJLVDW VXEPLWWHG WKH QHFHVVDU\\ ÀQDQFLDO LQIRUPDWLRQ DQG SURJUDPPH VFKHGXOHV WR WKH',
    r'L 7KHUH DUH FXUUHQWO\\ QR VSHFLÀF WHFKQLFDO FRQGLWLRQV WKDW \'LJLVDW ZRXOG KDYH WR FRPSO\\ ZLWK',
    r'UHTXLUHPHQWV RQFH WKH UHJXODWLRQV DUH ÀQDOL]HG',
    r'7KH IXOO LQIRUPDWLRQ RI WKH GHFLVLRQ FDQ EH REWDLQHG DW WKH RIÀFHV RI WKH \$XWKRULW\\',
    r'1DÀVK 7UDGLQJ \&\& W D \$PHVKR \)0',
    r'ZKLFK FDQ EH LQVSHFWHG DW WKH RIÀFHV RI WKH \$XWKRULW\\',
    r'%\\ KDQG WR WKH KHDG RIÀFHV RI WKH \$XWKRULW\\ QDPHO\\ \&RPPXQLFDWLRQ \+RXVH 5REHUW',
    r'%\\ SRVW WR WKH KHDG RIÀFHV RI WKH \$XWKRULW\\ QDPHO\\ 3ULYDWH %DJ :LQGKRHN',
    r'SXUVXDQW WR D PHHWLQJ KHOG EHWZHHQ WKH SDUWLHV ,%XUVW VWDWHG WKDW WKH OLFHQFH ZDV IRU D À\[HG',
    r'DSSOLFDEOH WR WKH WUDQVLWLRQ RI OLFHQFHV DQG VSHFLÀFDOO\\ WR \/LFHQFHV FRQWHPSODWHG LQ VHFWLRQV',
    r'RI ÀYH \\HDUV IURP GDWH XQOHVV UHYRNHG LQ WHUPV RI FRQGLWLRQ µ'
]

for p in garbled_patterns:
    for m in re.finditer(p, text):
        garbled = m.group(0)
        decoded = decode_garbled(garbled)
        text = text.replace(garbled, decoded)

with open('docs/gazettes/5667.md', 'w') as f:
    f.write(text)

